using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BookStore.RecreateDb
{
    class Titles
    {
        public static List<string> List = new List<string>
        {
            "My Darling Caroline",
"Friday Dreaming",
"The Veiled Bride",
"First Comes Marriage",
"Irresistible",
"Slightly Scandalous",
"The Proposal",
"Dreaming",
"A Scandalous Countess",
"Secrets of the Night",
"Bridal Favors",
"Jane Eyre",
"Beauty in Black",
"Only in my Dreams",
"Stealing Heaven",
"Lord of Scoundrels",
"The Sherbrooke Bride",
"Never a Gentleman",
"When You Wish",
"The Perfect Rake",
"A Gentleman Undone",
"Beauty and the Baron",
"The Raven Prince",
"Beast",
"The Ugly Duchess",
"Entwined",
"Moonlit",
"The Music of the Night",
"Suddenly You",
"The Mystery Kiss",
"The Cad",
"Blame It On Bath",
"Secret Fire",
"With This Kiss",
"Nine Rules to Break When Romancing a Duke",
"Once and Always",
"Heather and Velvet",
"Yours until Dawn",
"The Duchess War",
"The Rake",
"Dangerous",
"Ravished",
"Scandal",
"The Viscount Who Loved Me",
"Tapestry",
"The Lady's Tutor",
"The Lover",
"The Devil Earl",
"The Last Rogue",
"Dark Wager",
"Ruthless",
"Midnight Bandit",
"Midnight Lord",
"My Only Love",
"The Charm School",
"Bitterleaf",
"Patterns of Love",
"Once a Princess",
"Logan's Outlaw",
"Reason to Believe",
"Courting Miss Hattie",
"The Love Charm",
"Silver Lining",
"The Promise of Jenny Jones",
"Denim and Lace",
"Nobody's Angel",
"Forgiving",
"Morning Glory",
"His Secondhand Wife",
"Land of Dreams",
"Forever in Texas",
"The Blue Castle",
"Going Back",
"Aaron",
"An Unexpected Love",
"Get Lucky",
"Over the Edge",
"Shelter Mountain",
"Skin Deep",
"See Jane Score",
"Be My Wife",
"Just One of the Guys",
"Terrific Tom",
"Rumor Has It",
"Wild Rain",
"About That Night",
"Butterfly Tattoo",
"Infatuation",
"Miss Emmaline and The Archangel",
"Fallen From Grace",
"Morning Comes Softly",
"Beauty and the Badge",
"Call Me Irresistible",
"Heaven, Texas",
"Midnight Angel",
"Night Magic",
"Always a Lady",
"Because of You",
"The Crossroads Cafe"

        };
    }
}
