//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.CompositeTypeServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompositeTypeServiceReference.ICompositeTypeService")]
    public interface ICompositeTypeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompositeTypeService/CompositeType", ReplyAction="http://tempuri.org/ICompositeTypeService/CompositeTypeResponse")]
        Shared.ClassLibrary.CompositeType CompositeType(Shared.ClassLibrary.CompositeType type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompositeTypeService/CompositeType", ReplyAction="http://tempuri.org/ICompositeTypeService/CompositeTypeResponse")]
        System.Threading.Tasks.Task<Shared.ClassLibrary.CompositeType> CompositeTypeAsync(Shared.ClassLibrary.CompositeType type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompositeTypeService/EnumType", ReplyAction="http://tempuri.org/ICompositeTypeService/EnumTypeResponse")]
        Shared.ClassLibrary.Answer EnumType(bool ans);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompositeTypeService/EnumType", ReplyAction="http://tempuri.org/ICompositeTypeService/EnumTypeResponse")]
        System.Threading.Tasks.Task<Shared.ClassLibrary.Answer> EnumTypeAsync(bool ans);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompositeTypeServiceChannel : global::Client.CompositeTypeServiceReference.ICompositeTypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompositeTypeServiceClient : System.ServiceModel.ClientBase<global::Client.CompositeTypeServiceReference.ICompositeTypeService>, global::Client.CompositeTypeServiceReference.ICompositeTypeService {
        
        public CompositeTypeServiceClient() {
        }
        
        public CompositeTypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompositeTypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompositeTypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompositeTypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Shared.ClassLibrary.CompositeType CompositeType(Shared.ClassLibrary.CompositeType type) {
            return base.Channel.CompositeType(type);
        }
        
        public System.Threading.Tasks.Task<Shared.ClassLibrary.CompositeType> CompositeTypeAsync(Shared.ClassLibrary.CompositeType type) {
            return base.Channel.CompositeTypeAsync(type);
        }
        
        public Shared.ClassLibrary.Answer EnumType(bool ans) {
            return base.Channel.EnumType(ans);
        }
        
        public System.Threading.Tasks.Task<Shared.ClassLibrary.Answer> EnumTypeAsync(bool ans) {
            return base.Channel.EnumTypeAsync(ans);
        }
    }
}
