//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.CompositeTypeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Server.WebHost.Model")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Answer", Namespace="http://schemas.datacontract.org/2004/07/Server.WebHost.Model")]
    public enum Answer : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yes = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompositeTypeServiceReference.ICompositeTypeService")]
    public interface ICompositeTypeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompositeTypeService/CompositeType", ReplyAction="http://tempuri.org/ICompositeTypeService/CompositeTypeResponse")]
        Client.CompositeTypeServiceReference.CompositeType CompositeType(Client.CompositeTypeServiceReference.CompositeType type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompositeTypeService/CompositeType", ReplyAction="http://tempuri.org/ICompositeTypeService/CompositeTypeResponse")]
        System.Threading.Tasks.Task<Client.CompositeTypeServiceReference.CompositeType> CompositeTypeAsync(Client.CompositeTypeServiceReference.CompositeType type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompositeTypeService/EnumType", ReplyAction="http://tempuri.org/ICompositeTypeService/EnumTypeResponse")]
        Client.CompositeTypeServiceReference.Answer EnumType(bool ans);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompositeTypeService/EnumType", ReplyAction="http://tempuri.org/ICompositeTypeService/EnumTypeResponse")]
        System.Threading.Tasks.Task<Client.CompositeTypeServiceReference.Answer> EnumTypeAsync(bool ans);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompositeTypeServiceChannel : global::Client.CompositeTypeServiceReference.ICompositeTypeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompositeTypeServiceClient : System.ServiceModel.ClientBase<global::Client.CompositeTypeServiceReference.ICompositeTypeService>, global::Client.CompositeTypeServiceReference.ICompositeTypeService {
        
        public CompositeTypeServiceClient() {
        }
        
        public CompositeTypeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompositeTypeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompositeTypeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompositeTypeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client.CompositeTypeServiceReference.CompositeType CompositeType(Client.CompositeTypeServiceReference.CompositeType type) {
            return base.Channel.CompositeType(type);
        }
        
        public System.Threading.Tasks.Task<Client.CompositeTypeServiceReference.CompositeType> CompositeTypeAsync(Client.CompositeTypeServiceReference.CompositeType type) {
            return base.Channel.CompositeTypeAsync(type);
        }
        
        public Client.CompositeTypeServiceReference.Answer EnumType(bool ans) {
            return base.Channel.EnumType(ans);
        }
        
        public System.Threading.Tasks.Task<Client.CompositeTypeServiceReference.Answer> EnumTypeAsync(bool ans) {
            return base.Channel.EnumTypeAsync(ans);
        }
    }
}
