using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BookStore.RecreateDb
{
    class Titles
    {
        public static List<string> List = new List<string>
        {
            "enim. Curabitur",
            "nascetur ridiculus mus.",
            "ipsum primis",
            "enim non nisi.",
            "vitae nibh. Donec est mauris,",
            "dui. Fusce aliquam, enim nec",
            "varius. Nam porttitor",
            "aliquet molestie tellus. Aenean",
            "ac ipsum. Phasellus vitae",
            "lorem, sit",
            "fringilla est. Mauris eu",
            "euismod et,",
            "magna, malesuada",
            "rhoncus. Proin nisl sem, consequat",
            "a neque.",
            "magna a tortor.",
            "sit amet",
            "ultrices iaculis odio.",
            "sagittis felis. Donec",
            "auctor, velit eget laoreet posuere,",
            "vel, convallis in, cursus et,",
            "sed dolor. Fusce mi",
            "lobortis",
            "sit amet",
            "lacinia at,",
            "parturient montes, nascetur ridiculus",
            "morbi",
            "sem ut dolor",
            "libero",
            "a felis ullamcorper",
            "arcu ac",
            "sem. Nulla interdum. Curabitur dictum.",
            "Class aptent taciti",
            "nunc",
            "sodales.",
            "sed",
            "ultrices posuere cubilia Curae; Phasellus",
            "malesuada vel, venenatis vel, faucibus",
            "porttitor interdum.",
            "lectus rutrum urna,",
            "dictum. Proin",
            "risus. Nunc ac",
            "arcu. Vestibulum ut eros",
            "adipiscing. Mauris",
            "ipsum leo elementum",
            "orci",
            "bibendum",
            "Sed eu eros. Nam",
            "enim. Etiam gravida molestie arcu.",
            "eros. Nam",
            "Curabitur ut odio vel",
            "augue scelerisque mollis. Phasellus",
            "facilisis, magna tellus faucibus leo,",
            "facilisi.",
            "gravida sagittis. Duis gravida.",
            "Ut tincidunt vehicula risus. Nulla",
            "justo eu arcu. Morbi sit",
            "Donec tempus, lorem fringilla ornare",
            "elit. Nulla facilisi. Sed neque.",
            "sem semper erat, in",
            "faucibus orci",
            "Mauris eu turpis. Nulla aliquet.",
            "Phasellus ornare. Fusce mollis.",
            "rutrum urna, nec luctus felis",
            "malesuada fames ac",
            "aliquet nec, imperdiet",
            "bibendum sed, est. Nunc laoreet",
            "Proin",
            "Fusce diam nunc, ullamcorper",
            "id, ante.",
            "sit amet, consectetuer",
            "tempus mauris erat",
            "convallis convallis dolor. Quisque",
            "tincidunt aliquam",
            "scelerisque dui. Suspendisse",
            "auctor",
            "consectetuer rhoncus. Nullam velit",
            "accumsan sed, facilisis vitae,",
            "nibh dolor, nonummy",
            "aliquet,",
            "volutpat. Nulla dignissim.",
            "quam quis diam.",
            "pretium",
            "leo. Cras",
            "vulputate dui, nec tempus",
            "Donec egestas. Aliquam nec enim.",
            "Donec",
            "ligula tortor, dictum",
            "Vestibulum ante ipsum",
            "et arcu imperdiet",
            "auctor.",
            "elit. Curabitur sed",
            "mi lacinia mattis. Integer",
            "consectetuer, cursus et, magna. Praesent",
            "nisi.",
            "nulla ante, iaculis",
            "sapien, gravida non,",
            "sodales at,",
            "euismod urna. Nullam lobortis",
            "imperdiet dictum magna. Ut tincidunt",

        };
    }
}
